stages:
  - build

variables:
  DOCKER_TLS_CERTDIR: ''
  DOCKER_HOST: tcp://docker:2375

build_images:
  stage: build
  tags:
    - docker
  image: docker:26
  services:
    - name: docker:26-dind
      alias: docker
      command: ['--tls=false']
  script:
    - docker version
    - docker build -t autumn2025-frontend:ci ./frontend
    - docker build -t autumn2025-backend:ci ./backend
