services:
  postgres:
    image: postgres:16
    container_name: autumn2025-postgres
    environment:
      POSTGRES_DB: demo
      POSTGRES_USER: timur_eit
      POSTGRES_PASSWORD: postgres
    volumes:
      - postgres_data:/var/lib/postgresql/data
    restart: unless-stopped

  backend:
    image: registry.gitlab.com/timur-eit/itmo-autumn-2025/backend:latest
    container_name: autumn2025-backend
    depends_on:
      - postgres
    env_file:
      - ./backend/.env
    restart: unless-stopped

  frontend:
    image: registry.gitlab.com/timur-eit/itmo-autumn-2025/frontend:latest
    container_name: autumn2025-frontend
    depends_on:
      - backend
    ports:
      - "80:80"
    restart: unless-stopped

volumes:
  postgres_data:
